create table public.roomate_groups (
  roomate_group_id bigint generated by default as identity not null primary key,
  name text not null,
  active boolean not null default true,

  archived_at timestamp with time zone,
  updated_at timestamp with time zone not null default now()
);