create table public.listings (
  listingid bigint generated by default as identity not null,
  listing_name text null,
  description text null,
  preview_imgs array null,
  listing_type public.listingtype null,
  bedroom_count integer null,
  bath_count integer null,
  size_square_feet integer null,
  features array null,
  monthly_cost integer null,
  listed_at timestamp with time zone not null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone ('utc'::text, now()),
  street1 text null,
  street2 text null,
  city text null,
  state text null,
  zip text null,
  location geography not null,
  constraint listings_pkey primary key (listingid)
) tablespace pg_default;

create index if not exists listings_geo_index on public.listings using gist (location) tablespace pg_default;
